// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqqXnT4j1uI1vvtZioeYhO2ELciiGz5A',
    appId: '1:125898760820:web:2176102aafcc3ea6602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    authDomain: 'book-list-ebb15.firebaseapp.com',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    measurementId: 'G-8GWZ5JZ7PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRrVDI8TkZoojU84-qaR9A__dGdNReKo',
    appId: '1:125898760820:android:b3c0a80be1b61ee8602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTJJn_t5DQJn-JyMR7Bo6oRMiZxo42jI',
    appId: '1:125898760820:ios:a4b8f46318d0c93c602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    iosClientId: '125898760820-0grmb8clv20ione12bopnsi000t3l5ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpTJJn_t5DQJn-JyMR7Bo6oRMiZxo42jI',
    appId: '1:125898760820:ios:18acd2b1e6854055602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    iosClientId: '125898760820-q0nbp2ainj87nbjhb700o5i82ulaaur7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUZHdatz6Y7J7u_7CY4z58ooKKu8l2MM',
    appId: '1:125898760820:web:39d6bb35970da595602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    authDomain: 'book-list-ebb15.firebaseapp.com',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    measurementId: 'G-F0THHLY4JR',
  );
}
