// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqX9DDoHrgevPXZ0JU7mIBzcGBZYxxdOQ',
    appId: '1:106073751117:web:93f83039b966d539626604',
    messagingSenderId: '106073751117',
    projectId: 'todo-app-5f039',
    authDomain: 'todo-app-5f039.firebaseapp.com',
    storageBucket: 'todo-app-5f039.firebasestorage.app',
    measurementId: 'G-2ZK4BR47WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcA1WvKGuJoA2NotTpNgm_coPqhbJuIvM',
    appId: '1:106073751117:android:d8edbc4118e8211a626604',
    messagingSenderId: '106073751117',
    projectId: 'todo-app-5f039',
    storageBucket: 'todo-app-5f039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZXBfZ46Qcx4g_aWOqcN8jF9w-Xrjkp4',
    appId: '1:106073751117:ios:2ba8716f988b6770626604',
    messagingSenderId: '106073751117',
    projectId: 'todo-app-5f039',
    storageBucket: 'todo-app-5f039.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZXBfZ46Qcx4g_aWOqcN8jF9w-Xrjkp4',
    appId: '1:106073751117:ios:2ba8716f988b6770626604',
    messagingSenderId: '106073751117',
    projectId: 'todo-app-5f039',
    storageBucket: 'todo-app-5f039.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqX9DDoHrgevPXZ0JU7mIBzcGBZYxxdOQ',
    appId: '1:106073751117:web:e4176aa3eb4d8f06626604',
    messagingSenderId: '106073751117',
    projectId: 'todo-app-5f039',
    authDomain: 'todo-app-5f039.firebaseapp.com',
    storageBucket: 'todo-app-5f039.firebasestorage.app',
    measurementId: 'G-6ENQ6KKL7P',
  );
}
